// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NascentiaFlow.Entities;

#nullable disable

namespace NascentiaFlow.Migrations.Core
{
    [DbContext(typeof(CoreContext))]
    [Migration("20260619074323_AddActivity")]
    partial class AddActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NascentiaFlow.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FocusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FocusId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.BodyWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BodyWeights");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.Diary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Datetime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diaries");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.Focus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivityTypeId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("AvailablePoints")
                        .HasColumnType("REAL");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<float?>("GainedPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Focuses");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.Activity", b =>
                {
                    b.HasOne("NascentiaFlow.Entities.Focus", "Focus")
                        .WithMany()
                        .HasForeignKey("FocusId");

                    b.Navigation("Focus");
                });

            modelBuilder.Entity("NascentiaFlow.Entities.Focus", b =>
                {
                    b.HasOne("NascentiaFlow.Entities.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.Navigation("ActivityType");
                });
#pragma warning restore 612, 618
        }
    }
}
